### ISSUE TITLE
Evaluate for Spider - sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by gianfrancodemarco** [JBoRu/StructGPT#13]
Hello,

I'm trying to reproduce your results but I'm having trouble running evaluation scripts.
In particular, if I run __eval_spider_pred.sh__ or other Spider evaluation scripts I get the error:

```
Traceback (most recent call last):
  File "evaluate_for_spider.py", line 995, in <module>
    evaluate(path, db_dir, etype, kmaps, db_dir2)
  File "evaluate_for_spider.py", line 525, in evaluate
    schema = Schema(get_schema(db))
  File "/home/gianfranco/Desktop/uni/StructGPT/process_sql.py", line 88, in get_schema
    conn = sqlite3.connect(db)
sqlite3.OperationalError: unable to open database file
```

It seems that it is trying to open .sqlite files, but I can't find them.
Could you provide them or how to build them?

Thanks

**Comment by JBoRu** [comment]
Hi,
  Thanks for your attention! I apologize for the late reply! You should download the .sqlite files from the official Spider website (https://yale-lily.github.io/spider).
